// Licensed to Elasticsearch B.V. under one or more agreements.
// Elasticsearch B.V. licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type ExpectedEventType struct {
	Category string
	Type     string
	Version  string
}

type Field struct {
	ID          int64
	Name        string
	Version     string
	Type        string
	Level       string
	Short       sql.NullString
	Description sql.NullString
	IsArray     bool
	Example     sql.NullString
	SearchText  string
}

type FieldAllowedValue struct {
	FieldID     int64
	Name        string
	Description string
}

type FieldFieldset struct {
	FieldID    int64
	FieldsetID int64
}

type FieldsFt struct {
	SearchText string
}

type Fieldset struct {
	ID          int64
	Name        string
	Version     string
	Short       sql.NullString
	Description sql.NullString
	TopLevel    bool
}
