// Licensed to Elasticsearch B.V. under one or more agreements.
// Elasticsearch B.V. licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const insertExpectedEventType = `-- name: InsertExpectedEventType :exec
INSERT INTO
    expected_event_types (category, type, version)
VALUES (?, ?, ?)
`

type InsertExpectedEventTypeParams struct {
	Category string
	Type     string
	Version  string
}

func (q *Queries) InsertExpectedEventType(ctx context.Context, arg InsertExpectedEventTypeParams) error {
	_, err := q.db.ExecContext(ctx, insertExpectedEventType, arg.Category, arg.Type, arg.Version)
	return err
}

const insertField = `-- name: InsertField :one
INSERT INTO
    fields (name, version, type, level, short, description, is_array, example, search_text)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    RETURNING id
`

type InsertFieldParams struct {
	Name        string
	Version     string
	Type        string
	Level       string
	Short       sql.NullString
	Description sql.NullString
	IsArray     bool
	Example     sql.NullString
	SearchText  string
}

func (q *Queries) InsertField(ctx context.Context, arg InsertFieldParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertField,
		arg.Name,
		arg.Version,
		arg.Type,
		arg.Level,
		arg.Short,
		arg.Description,
		arg.IsArray,
		arg.Example,
		arg.SearchText,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertFieldAllowedValue = `-- name: InsertFieldAllowedValue :exec
INSERT INTO
    field_allowed_values (field_id, name, description)
VALUES (?, ?, ?)
`

type InsertFieldAllowedValueParams struct {
	FieldID     int64
	Name        string
	Description string
}

func (q *Queries) InsertFieldAllowedValue(ctx context.Context, arg InsertFieldAllowedValueParams) error {
	_, err := q.db.ExecContext(ctx, insertFieldAllowedValue, arg.FieldID, arg.Name, arg.Description)
	return err
}

const insertFieldFieldset = `-- name: InsertFieldFieldset :exec
INSERT INTO
    field_fieldsets (fieldset_id, field_id)
VALUES (?, ?)
`

type InsertFieldFieldsetParams struct {
	FieldsetID int64
	FieldID    int64
}

func (q *Queries) InsertFieldFieldset(ctx context.Context, arg InsertFieldFieldsetParams) error {
	_, err := q.db.ExecContext(ctx, insertFieldFieldset, arg.FieldsetID, arg.FieldID)
	return err
}

const insertFieldset = `-- name: InsertFieldset :one
INSERT INTO
    fieldsets (name, version, short, description, top_level)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type InsertFieldsetParams struct {
	Name        string
	Version     string
	Short       sql.NullString
	Description sql.NullString
	TopLevel    bool
}

func (q *Queries) InsertFieldset(ctx context.Context, arg InsertFieldsetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertFieldset,
		arg.Name,
		arg.Version,
		arg.Short,
		arg.Description,
		arg.TopLevel,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
