sudo: false

language: go

os:
- linux

go:
- 1.13.x

before_install:
- echo ENV $(env)
- echo PY3 $(which python3)
- echo PY37 $(which python3.7)
- make setup

addons:
  apt:
    sources:
      - deadsnakes # Python PPA
    update: true
    packages:
      - xsltproc
      - libxml2-utils
      - python3.7

jobs:
  include:
    - stage: check
      script:
      - make check
