sudo: false

language: go

os:
- linux

dist: bionic

go:
- 1.13.x

python:
- '3.7'

install:
- make setup

addons:
  apt:
    update: true
    packages:
      - xsltproc
      - libxml2-utils

jobs:
  include:
    - stage: check
      script:
      - make check
