sudo: false

language: go

os:
- linux

go:
- 1.10.x

before_install:
- make setup

jobs:
  include:
    - stage: check
      script:
      - make check
    - stage: docs
      script:
      - make docs
