sudo: false

language: go

os:
- linux

dist: bionic

go:
- 1.13.x

install:
- git fetch --tags --all
- make setup

addons:
  apt:
    update: true
    packages:
      - libxml2-utils
      - python3-venv
      - xsltproc

jobs:
  include:
    - stage: check
      script:
      - make check
