sudo: false

language: go

os:
- linux

go:
- 1.10.x

before_install:
- make setup

addons:
  apt:
    update: true
    packages:
      - xsltproc

jobs:
  include:
    - stage: check
      script:
      - make check
    - stage: docs
      script:
      - OPEN_DOCS="" make docs
