sudo: false

language: go

os:
- linux

go:
- 1.13.x
python:
- "3.7"

before_install:
# Force install Python 3.7
- sudo add-apt-repository -y ppa:deadsnakes/ppa
- sudo apt-get -q update
- sudo apt-get -yq install python3.7
# Normal
- make setup

addons:
  apt:
    update: true
    packages:
      - xsltproc
      - libxml2-utils

jobs:
  include:
    - stage: check
      script:
      - make check
