---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ecs
  description: Elastic Common Schema
spec:
  type: library
  owner: group:ecs
  lifecycle: production

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-ecs
  description: ECS unit tests and lint checks
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/ecs
spec:
  type: buildkite-pipeline
  owner: group:ecs
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: ecs
      description: ECS unit tests and lint checks
    spec:
      repository: elastic/ecs
      pipeline_file: ".buildkite/pipeline.yml"
      branch_configuration: "main 8.* 9.* 10.*"
      cancel_intermediate_builds: true
      cancel_intermediate_builds_branch_filter: '!main !8.* !9.*'
      skip_intermediate_builds: true
      skip_intermediate_builds_branch_filter: '!main !8.* !9.*'
      provider_settings:
        build_pull_requests: true
        build_pull_request_forks: false
        build_tags: false
      teams:
        ecs:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
