# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

steps:
  - label: ":python: Run tests (make check yamllint)"
    key: tests
    command: ".buildkite/scripts/run-tests.sh"
    agents:
      image: "docker.elastic.co/ci-agent-images/pipelib:0.33.0@sha256:d79a2f81e8679788e314bdb69c074388dbc9b5d6d30f9e2e90cd40b867911bf7"
      cpu: "2"
      memory: "2G"
