# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

steps:
  - label: ":python: Run tests (make check yamllint)"
    key: tests
    command: ".buildkite/scripts/run-tests.sh"
    agents:
      image: "docker.elastic.co/ci-agent-images/pipelib:0.32.0@sha256:508f620c3821579a7bac5347a85a9fa6a47f68e844083b976d928c41ae5c7bec"
      cpu: "2"
      memory: "2G"
