[[ecs-release-notes-8.2.0]]
=== 8.2.0

[[schema-changes-8.2.0]]
[float]
==== Schema changes

[[schema-added-8.2.0]]
[float]
===== Added

* Add beta `container.*` metric fields. {ecs_pull}1789[#1789]
* Add six new syslog fields to `log.syslog.*`. {ecs_pull}1793[#1793]
* Added `faas.id`, `faas.name` and `faas.version` fields as beta. {ecs_pull}1796[#1796]
* Added linux event model beta fields and reuses to support RFC 0030. {ecs_pull}1842[#1842], {ecs_pull}1847[#1847], {ecs_pull}1884[#1884]
* Added `threat.feed.dashboard_id`, `threat.feed.description`, `threat.feed.name`, `threat.feed.reference` fields. {ecs_pull}1844[#1844]

#### Improvements

* `email.*` field set now GA. {ecs_pull}1794[#1794], {ecs_pull}1841[#1841]

### Tooling and Artifact Changes

#### Added

* Adding optional field attribute, `pattern`. {ecs_pull}1834[#1834]
* Added support for re-using a fieldset as an array. {ecs_pull}1838[#1838]
* Added `--force-docs` option to generator. {ecs_pull}1879[#1879]

#### Improvements

* Update refs from master to main in USAGE.md etc {ecs_pull}1658[#1658]
* Clean up trailing spaces and additional newlines in schemas {ecs_pull}1667[#1667]
* Use higher compression as default in composable index template settings. {ecs_pull}1712[#1712]