[[ecs-threat-usage]]
==== Threat Fields Usage and Examples

* <<ecs-threat-usage-indicators>>
** <<ecs-threat-usage-indicators-network-example>>
** <<ecs-threat-usage-indicators-file-example>>

* <<ecs-threat-usage-enrichments>>

[discrete]
[[ecs-threat-usage-indicators]]
===== Indicators

Threat intelligence indicators come from many sources in different types and
formats. The ECS `threat.indicator.*` fields normalizes indicators to a common
format and enables consistent querying and use with indicator match rules.

Once collected, the threat intelligence data can be stored in a dedicated index
using the `threat.indicator.*` fields.

[discrete]
[[ecs-threat-usage-indicators-network-example]]
===== URL Abuse Network Indicator Example

```JSON
{
    "@timestamp": "2019-08-10T11:09:23.000Z",
    "event": { <1>
        "kind": "enrichment",
        "category": "threat", <2>
        "type": "indicator", <3>
        "severity": 7,
        "risk_score": 10.0,
    },
    "threat: {
        indicator": { <4>
            "first_seen": "2020-11-05T17:25:47.000Z",
            "last_seen": "2020-11-05T17:25:47.000Z",
            "modified_at": "2020-11-05T17:25:47.000Z",
            "sightings": 10,
            "type": [
                "ipv4-addr",
                "port",
                "domain-name",
                "email-addr"
            ],
            "description": "Email address, domain, port, and IP address observed during an Angler EK campaign.",
            "provider": "Abuse.ch",
            "reference": "https://urlhaus.abuse.ch/url/1292596/",
            "confidence": "High",
            "ip": 1.2.3.4,
            "domain": "malicious.evil",
            "port": 443,
            "email.address": "phish@malicious.evil",
            "marking: {
                tlp": "WHITE"
            },
            "scanner_stats": 4
        }
    },
    "related": { <5>
        "hosts": [
            "nefarious.evil"
        ],
        "ip": [
            1.2.3.4
        ]
    }
}
```
<1> Metadata about the indicator event.
<2> Using the `enrichment` value for `event.kind`.
<3> Using the `threat` value for `event.category`.
<4> Metadata about the indicator data.
<5> Any indicators should also be copied to relevant related.* fields.

[discrete]
[[ecs-threat-usage-indicators-file-example]]
===== File Example

```JSON
{
    "@timestamp": "2019-08-10T11:09:23.000Z",
    "event": {
        "kind": "enrichment",
        "category": "threat",
        "type": "indicator",
        "severity": 7,
        "risk_score": 10,
        },
    "threat": {
        "indicator": {
            "first_seen": "2020-11-05T17:25:47.000Z",
            "last_seen": "2020-11-05T17:25:47.000Z",
            "modified_at": "2020-11-05T17:25:47.000Z",
            "sightings": 10,
            "type": [
                "file" <1>
            ],
            "description": "Implant used during an Angler EK campaign.",
            "provider": "Abuse.ch",
            "reference": "https://bazaar.abuse.ch/sample/f3ec9a2f2766c6bcf8c2894a9927c227649249ac146aabfe8d26b259be7d7055",
            "confidence": "High",
            "file": { <2>
                "hash": {
                    "sha256": "0c415dd718e3b3728707d579cf8214f54c2942e964975a5f925e0b82fea644b4",
                     "md5": "1eee2bf3f56d8abed72da2bc523e7431"
                },
                "size": 656896,
                "name": "invoice.doc"
                },
            "marking": {
                "tlp": "WHITE"
            },
            "scanner_stats": 4
        }
    },
    "related": { <3>
        "hash": [
            "1eee2bf3f56d8abed72da2bc523e7431",
            "0c415dd718e3b3728707d579cf8214f54c2942e964975a5f925e0b82fea644b4"
        ]
    }
}
```
<1> Using the `file` value for `threat.indicator.type`.
<2> Attributes of the file are defined at `threat.indicator.file.*`
<3> Also populate the `related.hash` field with the file hashes.

[discrete]
[[ecs-threat-usage-enrichments]]
===== Enrichments
