// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by scripts/gocodegen.go - DO NOT EDIT.

package ecs

// The appliance fields contain the data about the hardware device, that
// collects, detects, or observes events on the network.
// Examples include web proxies, firewalls, routers and WiFi access points.
// Appliances may also run agents to collect event data generated by the
// device. ECS appliance.* fields shall be populated with details of the device
// which observed an event on the network.
type Appliance struct {
	// Unique identifier of this appliance.
	ID string `ecs:"id"`

	// Version of the appliance.
	Version string `ecs:"version"`

	// Name of the appliance, not any observed devices on the network.
	Name string `ecs:"name"`

	// Type of the appliance.
	Type string `ecs:"type"`

	// IP address of the appliance, not the observed network connections.
	// Can be one or multiple IPv4 or IPv6 addresses.
	IP string `ecs:"ip"`

	// Physical location of the application.
	Location string `ecs:"location"`
}
