// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by scripts/gocodegen.go - DO NOT EDIT.

package ecs

// Device fields are used to provide additional information about the device
// that is the source of the information. This could be a firewall, network
// device, etc.
type Device struct {
	// MAC address of the device
	MAC string `ecs:"mac"`

	// IP address of the device.
	IP string `ecs:"ip"`

	// Hostname of the device.
	Hostname string `ecs:"hostname"`

	// Device vendor information.
	Vendor string `ecs:"vendor"`

	// Device version.
	Version string `ecs:"version"`

	// Device serial number.
	SerialNumber string `ecs:"serial_number"`

	// The type of the device the data is coming from.
	// There is no predefined list of device types. Some examples are
	// `endpoint`, `firewall`, `ids`, `ips`, `proxy`.
	Type string `ecs:"type"`
}
