// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by scripts/gocodegen.go - DO NOT EDIT.

package ecs

import (
	"time"
)

// ELF events from VirusTotal Intelligence Live Hunt results.
type FileElf struct {
	// Extracted when possible from the file's metadata. Indicates when it was
	// built or compiled. It can also be faked by malware creators.
	CreationDate time.Time `ecs:"creation_date"`

	// Header information of the ELF file.
	Header map[string]interface{} `ecs:"header"`

	// Number of ELF Program Headers.
	NumberProgramHeaders int64 `ecs:"number_program_headers"`

	// Number of ELF Section Headers.
	NumberSectionHeaders int64 `ecs:"number_section_headers"`

	// Section information of the ELF file.
	Sections map[string]interface{} `ecs:"sections"`

	// List of exported element names and types
	Exports map[string]interface{} `ecs:"exports"`

	// List of imported element names and types
	Imports map[string]interface{} `ecs:"imports"`

	// List of shared libraries used by this ELF object
	SharedLibraries string `ecs:"shared_libraries"`

	// telfhash hash for ELF files.
	Telfhash string `ecs:"telfhash"`

	// ELF object segment list.
	SegmentList string `ecs:"segment_list"`
}
