// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by scripts/gocodegen.go - DO NOT EDIT.

package ecs

// The interface fields describe information about the configuration of an
// interface on any type of network connected host or observer.
// Interface configuration field requirements will vary significantly depending
// on the type of device being inventoried, or the interface specific
// information provided in a given event.
type Interface struct {
	// Interface ID as reported by the system.
	ID string `ecs:"id"`

	// Optional long interface name as reported by the systen.
	Name string `ecs:"name"`

	// Optional interface description as reported by the system.
	Description string `ecs:"description"`

	// Boolean value representing the logical state of the interface (true =
	// enabled, false = disabled)
	Enabled string `ecs:"enabled"`

	// Interface logical connection state as reported by the system. Possible
	// values are connected, not-connected, error-disabled
	Status string `ecs:"status"`

	// Interface speed as reported by the system in megabits per second.
	Speed string `ecs:"speed"`

	// Interface duplex setting as reported by the system.  Acceptable values
	// are full and half
	Duplex string `ecs:"duplex"`

	// Set this value to true if the interface is set for autonegotiation
	Negotiation string `ecs:"negotiation"`

	// Some interfaces, particularly in networking devices, have a bandwidth
	// setting that is used to define the logical bandwidth available on a
	// physical link when it differs from the physical media.  Record that
	// value in this field.
	Bandwidth string `ecs:"bandwidth"`
}
