// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by scripts/gocodegen.go - DO NOT EDIT.

package ecs

// The interface fields describe information about ingress and egress
// interfaces reported  by an observer.
type Interface struct {
	// Interface ID as reported by the system (typically SNMP interface ID).
	ID string `ecs:"id"`

	// Optional interface name as reported by the system.  Could be short
	// (eth0), long (gigabitethernet0/2),  or configured logical name (e.g.
	// outside, dmz).
	Name string `ecs:"name"`
}
