// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by scripts/gocodegen.go - DO NOT EDIT.

package ecs

// Risk score fields represent the normalized comparative sensitivity of an
// organization's resources.
// Risk scope fields used to categorize the business specific type of risk
// associated with a given asset, typically in reference  to the data housed in
// an asset or zone, or the level of access of a given user or group.
type Risk struct {
	// Comparative risk score assigned to resources based on a numerical scale,
	// quantitavely scoring the level  of risk represented by a possible
	// compriomise of the asset or data in question.
	// Recommended scale is 1-10, but 1-5 or 1-100 are also acceptable.
	Score int64 `ecs:"score"`

	// An array of one or more locally relevant terms to describe the audit
	// scope of the risk type associated with an asset. Typical values have
	// local significance relevant to e.g. a local data classification system
	// or regulatory/compliance  requirements like public, private,
	// confidential, pci, cfr21p11, pii, sox, gdpr, etc.
	Scope string `ecs:"scope"`
}
