// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by scripts/gocodegen.go - DO NOT EDIT.

package ecs

// ECS threat fields encompass detected suspicious activity (e.g. IDS alert,
// malware activity) typically reported by IDS/IPS and NGFWs, as well as threat
// intel/global IOC data ingested from a feed source like MISP or Anomali.
type Threat struct {
	// Threat ID, typically provided by reporting system or threat intel
	// provider.
	ID string `ecs:"id"`

	// Threat name as reported by system or intel provider
	Name string `ecs:"name"`

	// The type of tactic used by this threat. You can use the Mitre ATT&CK
	// Matrix Tactic categorization, for example. (ex.
	// https://attack.mitre.org/tactics/TA0040/ )
	Tactic string `ecs:"tactic"`

	// The type of technique used by this threat. You can use the Mitre ATT&CK
	// Matrix Tactic categorization, for example. (ex.
	// https://attack.mitre.org/techniques/T1499/ )
	Technique string `ecs:"technique"`

	// Textual description of the observed threat or threat intel that provides
	// more context
	Description string `ecs:"description"`

	// Typically a qualitative description of the risk associated with the
	// observed threat or IOC
	Severity string `ecs:"severity"`

	// Typically a qualitative description of the confidence that the threat
	// identification is  correct provided by the observer
	Confidence string `ecs:"confidence"`
}
