// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by scripts/gocodegen.go - DO NOT EDIT.

package ecs

// ECS threat fields encompass detected suspicious activity (e.g. IDS alert,
// malware activity) typically reported by IDS/IPS and NGFWs, as well as threat
// intel/global IOC data ingested from a feed source like MISP or Anomali.
type Threat struct {
	// Threat ID, typically provided by reporting system (e.g. NGFW or IDS) or
	// threat intel provider (Anomali, OTX, etc.)
	ID string `ecs:"id"`

	// Threat name, typically provided by reporting system (e.g. NGFW or IDS)
	// or threat intel provider (Anomali, OTX, etc.)
	Name string `ecs:"name"`

	// Name of the type of tactic used by this threat. You can use the Mitre
	// ATT&CK Matrix Tactic categorization, for example. (ex.
	// https://attack.mitre.org/tactics/TA0040/ )
	TacticName string `ecs:"tactic.name"`

	// The id of tactic used by this threat. You can use the Mitre ATT&CK
	// Matrix Tactic categorization, for example. (ex.
	// https://attack.mitre.org/tactics/TA0040/ )
	TacticID string `ecs:"tactic.id"`

	// The reference url of tactic used by this threat. You can use the Mitre
	// ATT&CK Matrix Tactic categorization, for example. (ex.
	// https://attack.mitre.org/tactics/TA0040/ )
	TacticReference string `ecs:"tactic.reference"`

	// The name of technique used by this threat. You can use the Mitre ATT&CK
	// Matrix Tactic categorization, for example. (ex.
	// https://attack.mitre.org/techniques/T1499/ )
	TechniqueName string `ecs:"technique.name"`

	// The id of technique used by this threat. You can use the Mitre ATT&CK
	// Matrix Tactic categorization, for example. (ex.
	// https://attack.mitre.org/techniques/T1499/ )
	TechniqueID string `ecs:"technique.id"`

	// The reference url of technique used by this threat. You can use the
	// Mitre ATT&CK Matrix Tactic categorization, for example. (ex.
	// https://attack.mitre.org/techniques/T1499/ )
	TechniqueReference string `ecs:"technique.reference"`

	// Textual description of the observed threat or threat intel that provides
	// more context
	Description string `ecs:"description"`

	// Typically a qualitative description of the risk associated with the
	// observed threat or IOC. The reported  severity and confidence fields can
	// be normalized to provide a threat.risk.score for the overall event.
	Severity string `ecs:"severity"`

	// Typically a qualitative description of the observing systems confidence
	// in the correct identification of a  threeat (more prevalent in AI/ ML
	// analysis) or confidence in a particular threat intel provider. The
	// reported  severity and confidence fields can be normalized to provide a
	// threat.risk.score for the overall event.
	Confidence string `ecs:"confidence"`
}
