// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by scripts/gocodegen.go - DO NOT EDIT.

package ecs

import (
	"time"
)

// These fields contain information about a thread.
// These fields provide more context about the relevant thread related to the
// data in the document.
type Thread struct {
	// Thread id.
	ID int64 `ecs:"id"`

	// Thread name.
	Name string `ecs:"name"`

	// The time the thread started.
	Start time.Time `ecs:"start"`

	// Memory address where the thread started.
	StartAddress string `ecs:"start_address"`

	// TODO
	StartAddressModule string `ecs:"start_address_module"`

	// Service associated with the thread.
	ServiceName string `ecs:"service_name"`
}
