// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by scripts/gocodegen.go - DO NOT EDIT.

package ecs

// These fields contain information about a token.
// These fields can help you correlate metrics information with a process
// id/name from a log message.  The `process.pid` often stays in the metric
// itself and is copied to the global field for correlation.
type Token struct {
	// Username of token owner.
	User string `ecs:"user"`

	// TODO
	Domain string `ecs:"domain"`

	// TODO
	Sid string `ecs:"sid"`

	// Type of the token, either primary or impersonation.
	Type string `ecs:"type"`

	// Impersonation level. Only valid for impersonation tokens.
	ImpersonationLevel string `ecs:"impersonation_level"`

	// Numeric integrity level.
	IntegrityLevel int64 `ecs:"integrity_level"`

	// Human readable integrity level.
	IntegrityLevelName string `ecs:"integrity_level_name"`

	// Whether or not this is an appcontainer token.
	IsAppcontainer bool `ecs:"is_appcontainer"`

	// Array describing the privileges associated with the token.
	Privileges map[string]interface{} `ecs:"privileges"`

	// Name of the privilege.
	PrivilegesName string `ecs:"privileges.name"`

	// Whether or not the privilege is enabled.
	PrivilegesEnabled bool `ecs:"privileges.enabled"`

	// Description of the privilege.
	PrivilegesDescription string `ecs:"privileges.description"`
}
