// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by scripts/gocodegen.go - DO NOT EDIT.

package ecs

// The VLAN fields describe information about the configuration of VLANs in an
// enterprise network.
// VLAN fields contain configuration information about virtiual LANs, with base
// identification fields (vlan.id, vlan.name) reuseable under source,
// destination, and interface fields when observers or hosts are providing
// relevant information in events (e.g. netflow, firewall logs, host and
// network metrics, etc.)
type Vlan struct {
	// VLAN ID of the congfigured VLAN. Expoected values are 0 to 4095, with 0
	// and 4095 typically being  reserved for system use, and not generally
	// reported.
	ID int32 `ecs:"id"`

	// VLAN name as configured on the device, or reported in the event.
	Name string `ecs:"name"`

	// VLAN SAID is a user configurable security association that may be
	// configured to allow various network security platforms to properly
	// identify traffic by VLAN.
	Said string `ecs:"said"`

	// Maximum tranmission unit is the maximum size of packets provcessed in
	// this VLAN.   This value will typically be in the range of 68 - 9216,
	// with 1400-1500 and 9216 being the most likely.
	Mtu string `ecs:"mtu"`

	// Current state of the VLAN as reported by the source device.
	State string `ecs:"state"`

	// the vlan.mode field is used to identify any non-standard or vendor
	// specific VLAN modes as configured. For example,  Cisco VLANs can be
	// configured to operate in "private" or "rspan" VLAN modes.  Standard VLAN
	// modes can leave  this field blank.
	Mode string `ecs:"mode"`
}
