---
- name: service
  footnote: >
    The service fields may be self-nested under service.origin.* and service.target.* to describe origin or target services in the context of incoming or outgoing requests, respectively.
    However, the fieldsets service.origin.* and service.target.* must not be confused with the root service fieldset that is used to describe the actual service under observation.
    The fieldset service.origin.* may only be used in the context of incoming requests or events to describe the originating service of the request.
    The fieldset service.target.* may only be used in the context of outgoing requests or events to describe the target service of the request.
  reusable:
    top_level: true
    expected:
      - at: service
        as: target
        short_override: Describes the target service in case of an outgoing request or event.
      - at: service
        as: origin
        short_override: Describes the origin service in case of an incoming request or event.
