---
- name: service
  reusable:
    top_level: true
    expected:
      - at: service
        as: target
        short_override: Target service of an invocation.
      - at: service
        as: origin
        short_override: Origin service of an invocation.
