title: Logging
name: logging
description:
  ECS fields used in logging use cases.
fields:
- name: base
  fields:
    - name: id
      type: keyword
      description: >
        Unique id of the log entry.
      example: 8a4f500d
    - name: timestamp
      type: date
      example: "2016-05-23T08:05:34.853Z"
      description: >
        Timestamp of the log line.
    - name: message
      type: text
      required: true
      example: "Hello World"
      description: >
        The log message.

        This can contain the full log line or based on the processing
        only the extracted message part. This is expected to be human readable.

    - name: hostname
      type: keyword
      example: "www.example.com"
      description: >
        Hostname extracted from the log line.
    - name: ip
      type: ip
      example: "192.168.1.12"
      description: >
        IP Address extracted from the log line. Can be IPv4 or IPv6.


- name: log
  fields:
    - name: level
      type: keyword
      description: >
        Log level field. Is expected to be `WARN`, `ERR`, `INFO` etc.
      example: ERR
    - name: line
      type: long
      description: >
        Line number the log event was collected from.
      example: 18
    - name: offset
      type: long
      description: >
        Offset of the log event.
      example: 12


- name: source
  description: >
    Describes from where the log entries come from.
  fields:
    - name: path
      type: keyword
      description: >
        File path of the file the data is harvested from.
      example: /var/log/test.log
