---
- name: base
  title: Base
  group: 1
  description: >
    The base set contains all fields which are on the top level. These fields are common across all types of events.
  fields:
    - name: "@timestamp"
      type: date
      required: true
      phase: 3
      example: "2016-05-23T08:05:34.853Z"
      description: >
        Date/time when the event originated.

        For log events this is the date/time when the event was generated, and
        not when it was read.

        Required field for all events.

    - name: tags
      type: keyword
      example: "[\"production\", \"env2\"]"
      description: >
        List of keywords used to tag each event.

    - name: labels
      type: object
      example: "{key1: value1, key2: value2}"
      description: >
        Key/value pairs.

        Can be used to add meta information to events. Should not contain nested
        objects. All values are stored as keyword.

        Example: `docker` and `k8s` labels.

    - name: message
      type: text
      phase: 1
      example: "Hello World"
      description: >
        For log events the message field contains the log message.

        In other use cases the message field can be used to concatenate
        different values which are then freely searchable. If multiple
        messages exist, they can be combined into one message.
