---
- name: package
  title: Package
  group: 2
  short: These fields contain information about an installed software package.
  description: >
    These fields contain information about an installed software package. It contains general information about a
    package, such as name, version or size. It also contains installation details, such as time, URL or
    user who installed the package.
  type: group
  fields:

    - name: id
      level: core
      type: keyword
      description: ID uniquely identifying the package accross different hosts.
      example: 9b52cc0d83f794f6fc6190f603fa2f62dd9aa2017165d19ff1d62742955a7a05

    - name: name
      level: core
      type: keyword
      description: Package name
      example: go

    - name: version
      level: core
      type: keyword
      description: Package version
      example: 1.12.9

    - name: description
      level: core
      type: keyword
      description: Description of the package.
      example: Open source programming language to build simple/reliable/efficient software.

    - name: size
      format: string
      level: core
      type: long
      description: Package size in bytes.
      example: 62231

    - name: installed
      level: core
      type: date
      description: Time when package was installed.

    - name: remote_repository
      level: core
      type: keyword
      description: Remote repository URL from where the package was installed.
      example: https://golang.org

    - name: architecture
      level: extended
      type: keyword
      description: Package architecture.
      example: runtime

    - name: build_version
      level: extended
      type: keyword
      description: Build version of the installed package, e.g. commit hash.
      example: 9b52cc0d83f794f6fc6190f603fa2f62dd9aa2017165d19ff1d62742955a7a05

    - name: build_time
      level: extended
      type: date
      description: Time when package was built.

    - name: checksum
      level: extended
      type: keyword
      description: Checksum of the installed package
      example: 9b52cc0d83f794f6fc6190f603fa2f62dd9aa2017165d19ff1d62742955a7a05

    - name: install_type
      level: extended
      type: keyword
      description: Indicating when the package was installed, e.g. at runtime or at buildtime.
      example: runtime

    - name: license
      level: extended
      type: keyword
      description: License under which the package was released.
      example: Apache License 2.0
