//[[ecs-guidelines]]
== Guidelines and Best Practices

The {ecs} schema serves best when you follow schema guidelines and best
practices.

[float]
=== General guidelines

* The document MUST have the `@timestamp` field.
* Use the {ref}/mapping-types.html[data types]
  defined for an ECS field.
* Use the `ecs.version` field to define which version of ECS is used.
* Map as many fields as possible to ECS.

[float]
==== Guidelines for writing fields

* All fields must be lower case
* Combine words using underscore
* No special characters except `_`

[float]
==== Guidelines for naming fields

* *Present tense.* Use present tense unless field describes historical information.
* *Singular or plural.* Use singular and plural names properly to reflect the field content. For example, use `requests_per_sec` rather than `request_per_sec`.
* *General to specific.* Organise the prefixes from general to specific to allow grouping fields into objects with a prefix like `host.*`.
* *Avoid repetition.* Avoid stuttering of words. If part of the field name is already in the prefix, do not repeat it. Example: `host.host_ip` should be `host.ip`.
* *Use prefixes.* Fields must be prefixed except for the base fields. For example, all `host` fields are prefixed with `host.`. 
See <<dot-notation>> for more details.
+
The document structure should be nested JSON objects. If you use Beats or
Logstash, the nesting of JSON objects is done for you automatically. If you're
ingesting to Elasticsearch using the API, your fields must be nested
objects, not strings containing dots.

* *Avoid abbreviations when possible*. A few exceptions like `ip` exist.



