:doctype: book
:ecs: ECS

include::{asciidoc-dir}/../../shared/versions.asciidoc[]
include::{asciidoc-dir}/../../shared/attributes.asciidoc[]

[[ecs-reference]]
== Elastic Common Schema (ECS) Reference

beta[]

The Elastic Common Schema (ECS) defines a common set of fields for
ingesting data into Elasticsearch. A common schema helps you correlate
data from sources like logs and metrics or IT operations
analytics and security analytics.

ECS is still under development and backward compatibility is not guaranteed. Any
feedback on the general structure, missing fields, or existing fields is
appreciated. For contributions please read the
https://github.com/elastic/ecs/blob/master/CONTRIBUTING.md[Contribution
Guidelines].

[float]
[[ecs-field-types]]
=== Types of fields

* *Core fields.* Fields that are most common across all use cases. 
Focus on populating these fields first. 

* *Extended fields.* Any fields that are not a core field. 
Extended fields may apply to more narrow use cases, or may be more open
to interpretation depending on the use case. Extended fields are more likely to
change over time.



include::fields.asciidoc[]
include::conventions.asciidoc[]
include::guidelines.asciidoc[]
include::convert.asciidoc[]
include::use-cases.asciidoc[]
include::faq.asciidoc[]
include::contributing.asciidoc[]
include::glossary.asciidoc[]

