[[ecs-oss-considerations]]
=== Considerations in OSS Clusters

NOTE: This section applies only to the Open Source, Apache 2.0 licensed distribution of the Elastic Stack. All Elasticsearch field types are available in the free, Basic licensed version.

Beginning with ECS 1.8.0, ECS uses advanced {ref-bare}/current/mapping-types.html[field types] not available in the Open Source licensed Elastic Stack. Users can achieve similar functionality by replacing some of the basic licensed data types with somewhat equivalent types available in the OSS release.

The following table details these field types and their respective fallback type:

[options="header"]
.Field Types and their Fallback Type
|=====
| Field Type | Fallback

// ===============================================================

| {ref-bare}/current/keyword.html#wildcard-field-type[wildcard]
| {ref-bare}/current/keyword.html[keyword]

// ===============================================================

| {ref-bare}/current/keyword.html#constant-keyword-field-type[constant_keyword]
| {ref-bare}/current/keyword.html[keyword]

|=====

Some components will self-manage type fallback. OSS-only Beats will perform the fallback automatically, and OSS-only Logstash will install an OSS-compatible ECS template. The ECS tooling introduced a flag, `--oss`, for users to generate OSS-only compatible Elasticsearch index templates. The ECS tooling {ecs_github_repo_link}/USAGE.md#oss[usage guide] contains a detailed example.

The use of fallback types does not constitute an official variant of ECS. It's a workaround suggested bringing most of the benefits of ECS to users of the Open Source distribution of the Elastic stack.
