[[ecs-basic-types]]
=== Basic Data Types

NOTE: This section only applies to users of the Apache 2.0 license, OSS-only distribution of the Elastic Stack. Users of the default distribution under the Elastic license have access to all data types.

Beginning in ECS 1.8.0, certain ECS fields adopt data types available only under the Basic license of the Elastic Stack. The OSS-only distribution does not have these data types available.

Open source users can still benefit from ECS normalization. Any basic data types can be replaced with an equivalent fallback type if one is available. If a field uses a data type with no fallback available, open source users should not populate that ECS field.

[options="header"]
.Basic Data Types and their Fallback Types
|=====
| Basic Data Type | Open Source Fallback

// ===============================================================

| {ref-bare}/current/keyword.html#wildcard-field-type[wildcard]
| {ref-bare}/current/keyword.html[keyword]

// ===============================================================

| {ref-bare}/current/keyword.html#constant-keyword-field-type[constant_keyword]
| {ref-bare}/current/keyword.html[keyword]

|=====

Depending on the method of data ingestion and template management, there are a few options for OSS-only distribution users to manage data type fallback:

* Apache 2.0 license OSS-only Beats will perform this fallback for users.
* Apache 2.0 license OSS-only Logstash will install an OSS-compatible ECS template.
* The ECS tooling provides a flag, `--oss`, as an option for OSS-only users to generate OSS-compatible index templates. The {ecs_github_repo_link}/USAGE.md#oss[ECS GitHub repo] has additional details on the flag's usage.

Support for these OSS-only fallback use cases are not to be considered an official variant of ECS but rather provided as a workaround.
