[[ecs-basic-types]]
=== Basic Data Types

NOTE: This section only applies to users of the open source, Apache 2.0 license version of the Elastic Stack. Users of the default, free distribution under the Basic license have access to all data types.

Beginning with ECS 1.8.0, some ECS fields will adopt data types offered only under the Basic license. Users of the open source, Apache 2.0 license version of the Elastic Stack will not have these data types available.

Open source users can still benefit from ECS normalization, but any basic types will need replaced with an equivalent fallback type (if available). These Basic data types may appear in ECS, and a fallback data type is listed if one is available.

[options="header"]
.Data Types and Fallback Types
|=====
| Basic Data Type | Open Source Fallback

// ===============================================================

| {ref}/keyword.html#wildcard-field-type[wildcard]
| {ref}/keyword.html[keyword]

// ===============================================================

| {ref}/keyword.html#constant-keyword-field-type[constant_keyword]
| {ref}/keyword.html[keyword]

|=====

Support for these open source types are not to be considered an official variant of ECS, but rather as a workaround.

* Open source, Apache 2.0 licensed Beats will perform this fallback for users.
* Open source, Apache 2.0 licensed Logstash will install an open source compatible ECS template.
* For users managing custom index templates, the ECS tooling provides the `--oss` flag.
