[[ecs-basic-types]]
=== Data Types

IMPORTANT: The limitations noted in this section apply to the OSS-only distribution of the Elastic Stack. The default distribution with the Elastic license supports all data type used by ECS.

Beginning with ECS 1.8.0, the ECS specification adopted additional Elasticsearch {ref-bare}/current/mapping-types.html[data types] only available in the default distribution of the Elastic Stack.

OSS-only users can still benefit from normalizing data to ECS. Some licensed data types will have a fallback, but OSS-only users will not populate a field if a fallback is not available.

The following table details the additional types and their respective fallback type:

[options="header"]
.Data Types and their Fallback Type
|=====
| Data Type | Fallback

// ===============================================================

| {ref-bare}/current/keyword.html#wildcard-field-type[wildcard]
| {ref-bare}/current/keyword.html[keyword]

// ===============================================================

| {ref-bare}/current/keyword.html#constant-keyword-field-type[constant_keyword]
| {ref-bare}/current/keyword.html[keyword]

|=====

Some components will self-manage type fallback. OSS-only Beats will perform the fallback automatically, and OSS-only Logstash will install an OSS-compatible ECS template. The ECS tooling introduced a flag, `--oss`, for users to generate OSS-only compatible Elasticsearch index templates. The ECS tooling {ecs_github_repo_link}/USAGE.md#oss[usage guide] contains a detailed example.

The use of fallback types are not a supported, official ECS variant but instead provided as a workaround.
