[[ecs-tracing-usage]]
==== Tracing Usage

A trace describes the individual operations, and their causality, that ensue as a result of a single logical 
operation. A distributed trace comprises operations across multiple distributed components, crossing process, 
network, and security boundaries.

For example, a distributed trace may be initiated when someone presses a button to start an action on a website - in this example, 
the trace will represent calls made between the downstream services that handled the chain of requests initiated by this 
button being pressed.

A trace is made up of spans (and transactions), where each span (or transaction) is one part of the processing. Usually a span (or transaction) corresponds to one request to a
component, but not always. Sometimes a component may break up processing into multiple spans (and transactions) if needed. 

The spans (and transactions) form a tree (or directed acylic grapph), with each span (or transaction), except the root, having a parent.

The `trace.id` allows the distributed trace messages to be correlated across an entire logical operation.

The `span.id` allows messages from a single section of processing within the overall trace, e.g. a request to a component, to be correlated together. The `transaction.id` is the equivalent for transactions.

If following the https://www.w3.org/TR/trace-context/[W3C Trace Context Recommendation] then
the values should correspond to those specified in the recommendation and passed in the `traceparent` header, 
with `trace.id` being 32 lowercase hex characters, and `span.id` being 16 lowercase hex characters.

For correlation wtih Elastic Application Performance Monitoring (APM) see 
the https://www.elastic.co/guide/en/apm/get-started/current/distributed-tracing.html[APM Distributed Tracing] documentation.

===== Example

The following is an example **Trace** made up of 6 **Spans**:

------------------------------------------------------------------
Causal relationships between Spans in a single Trace

       [Span A]  ←←←(the root span)
           |
    +------+------+
    |             |
[Span B]      [Span C] ←←←(Span C is a `child` of Span A)
    |             |
[Span D]      +---+-------+
              |           |
          [Span E]    [Span F]
------------------------------------------------------------------

Sometimes it's easier to visualize **Traces** with a time axis as in the diagram
below:

------------------------------------------------------------------
Temporal relationships between Spans in a single Trace

––|–––––––|–––––––|–––––––|–––––––|–––––––|–––––––|–––––––|–> time

[Span A···················································]
[Span B··············································]
    [Span D··········································]
    [Span C········································]
        [Span E·······]        [Span F··]
------------------------------------------------------------------

Diagrams taken from the https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/overview.md[OpenTelemetry specification overview] 
(which is also Apache 2.0 licensed).
