name: Build ecs-typescript and create updated definitions PR
on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2
        with:
          app-id: ${{ secrets.OBS_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.OBS_AUTOMATION_APP_PEM }}
          permission-actions: write
          repositories: |
            ecs-typescript

      - name: Trigger workflow on ecs-typescript
        env:
          GH_TOKEN: ${{ steps.get_token.outputs.token }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GH_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/elastic/ecs-typescript/actions/workflows/generate.yml/dispatches \
          -d '{"ref":"main","inputs":{"ecsRef":"${{ github.event.release.tag_name }}"}}'
