name: Build ecs-typescript and create updated definitions PR
on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Trigger workflow on ecs-typescript
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ECS_TYPESCRIPT_REPO_TRIGGER_KEY }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/elastic/ecs-typescript/actions/workflows/generate.yml/dispatches \
          -d '{"ref":"main","inputs":{"ecsRef":"${{ env.RELEASE_VERSION }}"}}'
