name: Docs Preview Comment

on:
  pull_request_target:
    types: [opened]
    paths:
      - docs/**

jobs:
  doc-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        name: Add doc preview links
        with:
          script: |
            const pr = context.payload.pull_request;
            const comment = `Documentation changes preview: https://${context.repo.repo}_bk_${pr.number}.docs-preview.app.elstc.co/diff`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
