name: docs-build
on:
  pull_request:
    branches: [main, '[0-9]+.[0-9]+']
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+'
  merge_group: ~
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    uses: elastic/docs-actions/.github/workflows/docs-build.yml@95505a414fa14c79e491ee6666a5a728190e1729 # v1
    with:
      enable-vale-linting: true
