---
name: github-commands-comment

on:
  pull_request_target:
    types:
      - opened

permissions:
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: elastic/oblt-actions/elastic/github-commands@9e2226b8a321731893ff5165a6981ee6da0bb280 # v1
