name: Manage stale pull requests

on:
  schedule:
  - cron: "0 0 * * *"

permissions:
  pull-requests: write

jobs:
  stale:
    if: github.repository == 'elastic/ecs'

    runs-on: ubuntu-latest

    steps:
    - name: "Check PRs"
      uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10.2.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: |
          Hi!

          We just realized that we haven't looked into this PR in a while. We're
          sorry!

          We're labeling this PR as `Stale` to make it hit our filters and
          make sure we get back to it as soon as possible. In the meantime, it'd
          be extremely helpful if you could take a look at it as well and confirm its
          relevance. A simple comment with a nice emoji will be enough `:+1`.

          If there is no activity on this PR within the **next 2 weeks**, it will be
          automatically closed.

          Thank you for your contribution!
        close-pr-message: |
          This PR has been automatically closed due to inactivity. If you'd like to
          continue working on this, feel free to re-open the PR or create a new one.

          Thank you for your contribution!
        stale-pr-label: 'stale'
        ascending: true
        days-before-pr-stale: 30
        days-before-issue-stale: -1
        days-before-close: 15
        operations-per-run: 120
