name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-24.04
    name: Unit Tests
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.x'
      - run: git fetch --prune --unshallow --tags
      - run: make check yamllint
